#!/usr/bin/env python
# encoding: utf-8
#
# Alert you when battery status are low
#
# Dependencies: pygtk pynotify
#
# "batterypunish" is a python module that notify on the screen
# a message alert when the charge of battery is at 10 %.
# Use the 'pynotify' library to create and notify a small graphical notification
# on the screen.
#
#

import pygtk
pygtk.require('2.0')
import pynotify
import sys
import time

# function to calculate te battery status (in percent)
def percent_battery_and_status():
    
    # read the file 'charge_full' located in BAT0 directory system
    with open ("/sys/class/power_supply/BAT0/charge_full", "r") as myfile:
        max_charge = myfile.read()
        max_ch = float(max_charge)
        print max_charge
    
    # read the file 'charge_now' located in BAT0 directory system
    with open ("/sys/class/power_supply/BAT0/charge_now", "r") as myfile:
        charge_now = myfile.read()
        ch_now = float(charge_now)
        print charge_now

    # read the file 'status' located in BAT0 directory system
    with open ("/sys/class/power_supply/BAT0/status", "r") as myfile:
        status = myfile.read()
        print status
            
    # calculate the real time percent of the battery
    percent = (ch_now / max_ch) * 100
    
    return (percent, status)
  

# MAIN
def main():

    chk = False
    x = 3
    b_status = "Discharging\n"
    lev_down_batt = 10.0

    # infinite loop
    while(True):

        # call function percent_battery - return batery percent and the status
        batt, status = percent_battery_and_status()

        # check status and level of battery charge
        if status == b_status and batt <= lev_down_batt:
            
            # init pynotify
            if not pynotify.init("BATTERY"):
                sys.exit(1)

            # must notify - battery charge is low
            if not chk and x > 0:
                n = pynotify.Notification("WARNING !!!", "Battery charge low. Please recharge immediately", "/usr/share/pixmaps/punisher_icon.png")
                n.set_urgency(pynotify.URGENCY_CRITICAL)
                if not n.show():
                    print "Failed to send notification"
                    sys.exit(1)
                x -= 1
                time.sleep(10)
                if x == 0:
                    chk = True
        else:
            chk = False

        # control every 10 seconds
        time.sleep(10)

    return 0


if __name__ == '__main__':main()
